// web/src/lib/components/pages/Auth.svelte
<script lang="ts">
  import { navigate } from 'svelte-routing';
  import { authStore } from '$lib/stores/auth';
  import { authApi } from '$lib/api/auth';
  import { toastStore } from '$lib/utils/toast';
  import Button from '$lib/components/ui/Button.svelte';
  import Input from '$lib/components/ui/Input.svelte';
  import Label from '$lib/components/ui/Label.svelte';

  let activeTab: 'login' | 'register' = 'login';
  let loading = false;

  // 登录表单
  let loginUsername = '';
  let loginPassword = '';

  // 注册表单
  let registerUsername = '';
  let registerEmail = '';
  let registerPassword = '';

  async function handleLogin() {
    if (!loginUsername || !loginPassword) {
      toastStore.show('请填写用户名和密码', 'error');
      return;
    }

    loading = true;
    try {
      const response = await authApi.login(loginUsername, loginPassword);
      authStore.login(response.token, response.user);
      toastStore.show('登录成功', 'success');
      navigate('/', { replace: true });
    } catch (error: any) {
      toastStore.show(error.message || '登录失败', 'error');
    } finally {
      loading = false;
    }
  }

  async function handleRegister() {
    if (!registerUsername || !registerEmail || !registerPassword) {
      toastStore.show('请填写所有必填字段', 'error');
      return;
    }

    loading = true;
    try {
      await authApi.register(registerUsername, registerEmail, registerPassword);
      toastStore.show('注册成功，请登录', 'success');
      activeTab = 'login';
      // 清空注册表单
      registerUsername = '';
      registerEmail = '';
      registerPassword = '';
    } catch (error: any) {
      toastStore.show(error.message || '注册失败', 'error');
    } finally {
      loading = false;
    }
  }
</script>

<div class="bg-gray-900 text-gray-200 min-h-screen flex items-center justify-center">
  <div class="container mx-auto px-6 py-12 max-w-md">
    <div class="bg-gray-800 rounded-lg shadow-2xl p-8 border border-gray-700">
      <!-- 标签页 -->
      <div class="flex mb-8">
        <button
          class="flex-1 py-3 text-center rounded-l-lg transition-colors duration-200 {activeTab === 'login'
            ? 'bg-blue-600 text-white'
            : 'bg-dark-300 text-gray-300'}"
          on:click={() => (activeTab = 'login')}
        >
          登录
        </button>
        <button
          class="flex-1 py-3 text-center rounded-r-lg transition-colors duration-200 {activeTab === 'register'
            ? 'bg-blue-600 text-white'
            : 'bg-dark-300 text-gray-300'}"
          on:click={() => (activeTab = 'register')}
        >
          注册
        </button>
      </div>

      {#if activeTab === 'login'}
        <!-- 登录表单 -->
        <form class="space-y-5" on:submit|preventDefault={handleLogin}>
          <div>
            <Label for="login-username" required>用户名</Label>
            <Input
              id="login-username"
              type="text"
              bind:value={loginUsername}
              required
            />
          </div>
          <div>
            <Label for="login-password" required>密码</Label>
            <Input
              id="login-password"
              type="password"
              bind:value={loginPassword}
              required
            />
          </div>
          <div class="pt-2">
            <Button
              type="submit"
              variant="primary"
              disabled={loading}
              class="w-full"
            >
              {loading ? '登录中...' : '登录'}
            </Button>
          </div>
        </form>
      {:else}
        <!-- 注册表单 -->
        <form class="space-y-5" on:submit|preventDefault={handleRegister}>
          <div>
            <Label for="reg-username" required>用户名</Label>
            <Input
              id="reg-username"
              type="text"
              bind:value={registerUsername}
              required
            />
          </div>
          <div>
            <Label for="reg-email" required>邮箱</Label>
            <Input
              id="reg-email"
              type="email"
              bind:value={registerEmail}
              required
            />
          </div>
          <div>
            <Label for="reg-password" required>密码</Label>
            <Input
              id="reg-password"
              type="password"
              bind:value={registerPassword}
              required
            />
          </div>
          <div class="pt-2">
            <Button
              type="submit"
              variant="primary"
              disabled={loading}
              class="w-full"
            >
              {loading ? '注册中...' : '注册'}
            </Button>
          </div>
        </form>
      {/if}
    </div>
  </div>
</div>

// web/src/pages/Auth.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '@/lib/stores/auth';
import { authApi } from '@/lib/api/auth';
import { toast } from '@/lib/stores/toast';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ThemeToggle } from '@/components/theme-toggle';

export function Auth() {
  const navigate = useNavigate();
  const { setAuth } = useAuthStore();
  const [isLogin, setIsLogin] = useState(true);
  const [formData, setFormData] = useState({
    username: '',
    email: '',
    password: '',
    confirmPassword: '',
  });
  const [twoFactorCode, setTwoFactorCode] = useState('');
  const [tempToken, setTempToken] = useState('');
  const [showTwoFactor, setShowTwoFactor] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!isLogin && formData.password !== formData.confirmPassword) {
      toast.error('两次输入的密码不一致');
      return;
    }

    try {
      if (isLogin) {
        const response = await authApi.login(formData.username, formData.password);

        if (response.requires_2fa) {
          setTempToken(response.token || '');
          setShowTwoFactor(true);
          toast.info('请输入双因素认证码');
        } else {
          const token = response.access_token || response.token;
          if (token && response.user) {
            setAuth(response.user, token);
            toast.success('登录成功');
            navigate('/');
          }
        }
      } else {
        const response = await authApi.register(
          formData.username,
          formData.email,
          formData.password
        );
        toast.success(response.message || '注册成功，请登录');
        setIsLogin(true);
        setFormData({ ...formData, password: '', confirmPassword: '' });
      }
    } catch (error: any) {
      toast.error(error.message || (isLogin ? '登录失败' : '注册失败'));
    }
  };

  const handleTwoFactorSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    try {
      const response = await authApi.verify2FA(tempToken, twoFactorCode);
      const token = response.access_token || response.token;
      if (token && response.user) {
        setAuth(response.user, token);
        toast.success('验证成功');
        navigate('/');
      }
    } catch (error: any) {
      toast.error(error.message || '验证失败');
    }
  };

  if (showTwoFactor) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <div className="absolute top-4 right-4">
          <ThemeToggle />
        </div>
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>双因素认证</CardTitle>
            <CardDescription>请输入您的认证器应用中的 6 位验证码</CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleTwoFactorSubmit} className="space-y-4">
              <div>
                <Label htmlFor="code" required>
                  验证码
                </Label>
                <Input
                  id="code"
                  type="text"
                  placeholder="000000"
                  maxLength={6}
                  value={twoFactorCode}
                  onChange={(e) => setTwoFactorCode(e.target.value)}
                  required
                />
              </div>
              <div className="flex gap-2">
                <Button type="button" variant="outline" onClick={() => setShowTwoFactor(false)} className="flex-1">
                  返回
                </Button>
                <Button type="submit" className="flex-1">
                  验证
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      <div className="absolute top-4 right-4">
        <ThemeToggle />
      </div>
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>{isLogin ? '登录' : '注册'} PMER</CardTitle>
          <CardDescription>
            {isLogin ? '欢迎回来' : '创建您的账户'}
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="username" required>
                用户名
              </Label>
              <Input
                id="username"
                type="text"
                value={formData.username}
                onChange={(e) =>
                  setFormData({ ...formData, username: e.target.value })
                }
                required
              />
            </div>

            {!isLogin && (
              <div>
                <Label htmlFor="email" required>
                  邮箱
                </Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) =>
                    setFormData({ ...formData, email: e.target.value })
                  }
                  required
                />
              </div>
            )}

            <div>
              <Label htmlFor="password" required>
                密码
              </Label>
              <Input
                id="password"
                type="password"
                value={formData.password}
                onChange={(e) =>
                  setFormData({ ...formData, password: e.target.value })
                }
                required
              />
            </div>

            {!isLogin && (
              <div>
                <Label htmlFor="confirmPassword" required>
                  确认密码
                </Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  value={formData.confirmPassword}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      confirmPassword: e.target.value,
                    })
                  }
                  required
                />
              </div>
            )}

            <Button type="submit" className="w-full">
              {isLogin ? '登录' : '注册'}
            </Button>

            <div className="text-center text-sm text-muted-foreground">
              {isLogin ? '还没有账户？' : '已有账户？'}
              <Button
                type="button"
                variant="link"
                className="p-0 ml-1"
                onClick={() => {
                  setIsLogin(!isLogin);
                  setFormData({
                    username: '',
                    email: '',
                    password: '',
                    confirmPassword: '',
                  });
                }}
              >
                {isLogin ? '立即注册' : '立即登录'}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
