// web/src/App.tsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { ThemeProvider } from './components/theme-provider';
import { Toaster } from './components/ui/toast';
import { useAuthStore } from './lib/stores/auth';
import { Auth } from './pages/Auth';
import { Passwords } from './pages/Passwords';
import { Commands } from './pages/Commands';
import { Profile } from './pages/Profile';
import { SetupTwoFactor } from './pages/SetupTwoFactor';

function ProtectedRoute({ children }: { children: React.ReactNode }) {
  const { isAuthenticated } = useAuthStore();

  if (!isAuthenticated) {
    return <Navigate to="/auth" replace />;
  }

  return <>{children}</>;
}

function App() {
  const { isAuthenticated } = useAuthStore();

  return (
    <ThemeProvider>
      <BrowserRouter>
        <Routes>
          <Route
            path="/auth"
            element={
              isAuthenticated ? <Navigate to="/" replace /> : <Auth />
            }
          />
          <Route
            path="/"
            element={
              <ProtectedRoute>
                <Passwords />
              </ProtectedRoute>
            }
          />
          <Route
            path="/commands"
            element={
              <ProtectedRoute>
                <Commands />
              </ProtectedRoute>
            }
          />
          <Route
            path="/profile"
            element={
              <ProtectedRoute>
                <Profile />
              </ProtectedRoute>
            }
          />
          <Route
            path="/setup-2fa"
            element={<SetupTwoFactor />}
          />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </BrowserRouter>
      <Toaster />
    </ThemeProvider>
  );
}

export default App;

// web/src/App.svelte
<script lang="ts">
  import { Router, Route, navigate } from 'svelte-routing';
  import { onMount } from 'svelte';
  import { authStore } from '$lib/stores/auth';
  import Toast from '$lib/components/ui/Toast.svelte';
  import Auth from '$lib/components/pages/Auth.svelte';
  import Passwords from '$lib/components/pages/Passwords.svelte';
  import Commands from '$lib/components/pages/Commands.svelte';

  onMount(() => {
    // 检查初始路由
    const isAuthenticated = $authStore.isAuthenticated;
    const currentPath = window.location.pathname;

    if (!isAuthenticated && currentPath !== '/auth') {
      navigate('/auth', { replace: true });
    } else if (isAuthenticated && currentPath === '/auth') {
      navigate('/', { replace: true });
    }
  });
</script>

<Router>
  <div>
    <Route path="/auth" component={Auth} />
    <Route path="/" component={Passwords} />
    <Route path="/commands" component={Commands} />
  </div>
</Router>

<Toast />
